# Site settings
title: ANDREW  BLOGğŸ“
description: "Java, Springì„ ì¢‹ì•„í•©ë‹ˆë‹¤."

baseurl: ""
url: "https://umanking.github.io"

# Google Analytics
google_analytics: UA-130245279-5

# Author
author:
  name: Andrew
  url: https://umanking.github.io
  email: umanking@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-toc
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:title
# permalink: /:year/:month/:day/:title
# permalink: date
paginate: 15

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]
# Disqus (Set to your disqus id)
# disqus:         jekyll-tale
